services:
  - type: web
    name: my-django-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: DjangoProject.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
