# Generated by Django 5.1.7 on 2025-04-25 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_surveyresponse"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalorieCalculatorResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Мужской"), ("female", "Женский")],
                        max_length=10,
                    ),
                ),
                ("height", models.FloatField(help_text="Рост в см")),
                ("weight", models.FloatField(help_text="Вес в кг")),
                (
                    "activity_level",
                    models.CharField(
                        choices=[
                            ("sedentary", "Минимальная активность"),
                            ("light", "Легкая активность"),
                            ("moderate", "Умеренная активность"),
                            ("active", "Высокая активность"),
                            ("very_active", "Очень высокая активность"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        choices=[
                            ("lose", "Похудение"),
                            ("maintain", "Поддержание веса"),
                            ("gain", "Набор массы"),
                        ],
                        max_length=10,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="SurveyResponse",
        ),
    ]
